### ISSUE TITLE
Update antlr4 dependency to the latest version

### ISSUE THREAD

**Issue by ToddFincannonEI** [climateinteractive/antlr4-vensim#10]
The antlr4 package the parser is based on has not been updated in a while. Update it to the latest version and test against the SDEverywhere sample models and current apps.

**Comment by ToddFincannonEI** [comment]
I updated the version to 0.6.1 after rebuilding the parser with antlr4 version 4.12.0. Model tests pass except for some expected errors using SDEverywhere compile version 0.7.5.

**Comment by chrispcampbell** [comment]
@ToddFincannonEI:

> Model tests pass except for some expected errors using SDEverywhere compile version 0.7.5.

Just to be clear, by "expected errors" do you mean the ones that are expected by the tests (but reported to the console, like in the `directconst_invalidcell` and `flatten` tests)?  If so, then that all sounds OK.

I ran the full SDE test suite against your latest antlr4-vensim branch and all looks OK.

**Comment by ToddFincannonEI** [comment]
Yes, that was what I meant by expected errors. Maybe that's the wrong term, since the tests pass.

**Comment by chrispcampbell** [comment]
OK, got it.  Just wanted to make sure there was another class of errors I wasn't seeing.  Not sure there's a better term :)
